# Details of the database connection to use for running unit tests.
test:
  adapter: mysql
  encoding: utf8
  database: invoicing_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
